spring:
  application:
    name: shop-zuul

zuul:
  routes:
    # 别名，无固定形式（一般使用服务名）
    server:
      # 绑定服务
      serviceId: user
      # 设置服务访问路径
      path: /use/**
  # 前缀
  prefix: /v1
  # 忽略所有默认路径（单一入口）
  ignored-services: "*"