spring:
  application:
    name: zuul-server

zuul:
  routes:
    # 别名，无固定形式（一般使用服务名）
    p1:
      # 绑定服务
      serviceId: p1
      # 设置服务访问路径
      path: /p1/**
  # 接口路径
  servlet-path: /lidaye
  # 忽略所有默认路径（单一入口）
  ignored-services: "*"
